package jp.takuya152005.entities.dao;

import java.util.List;

import jp.takuya152005.entities.dto.IUserBookmark;
import jp.takuya152005.entities.dto.IUserBookmarkExample;
import jp.takuya152005.entities.dto.IUserBookmarkKey;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IUserBookmarkDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int countByExample(IUserBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int deleteByExample(IUserBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(IUserBookmarkKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int insert(IUserBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int insertSelective(IUserBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	List<IUserBookmark> selectByExampleWithRowbounds(IUserBookmarkExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	List<IUserBookmark> selectByExample(IUserBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	IUserBookmark selectByPrimaryKey(IUserBookmarkKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") IUserBookmark record, @Param("example") IUserBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") IUserBookmark record, @Param("example") IUserBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(IUserBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user_bookmark_0
	 * @mbggenerated
	 */
	int updateByPrimaryKey(IUserBookmark record);

	/**
	 * �?��化けテス�?
	 *
	 */
	void test();
}
