package jp.takuya152005.entities.dao;

import java.util.List;
import jp.takuya152005.entities.dto.IUser;
import jp.takuya152005.entities.dto.IUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.takuya152005.entities.dto.IUserKey;

public interface IUserDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int countByExample(IUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int deleteByExample(IUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(IUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int insert(IUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int insertSelective(IUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	List<IUser> selectByExampleWithRowbounds(IUserExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	List<IUser> selectByExample(IUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	IUser selectByPrimaryKey(IUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") IUser record, @Param("example") IUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") IUser record, @Param("example") IUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(IUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(IUser record);
}