package jp.takuya152005.entities.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	private Integer tableNameSuffix;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public IUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public Integer getTableNameSuffix() {
		return tableNameSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void setTableNameSuffix(Integer tableNameSuffix) {
		this.tableNameSuffix = tableNameSuffix;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table i_user
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdIsNull() {
			addCriterion("md5_user_id is null");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdIsNotNull() {
			addCriterion("md5_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdEqualTo(String value) {
			addCriterion("md5_user_id =", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdNotEqualTo(String value) {
			addCriterion("md5_user_id <>", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdGreaterThan(String value) {
			addCriterion("md5_user_id >", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdGreaterThanOrEqualTo(String value) {
			addCriterion("md5_user_id >=", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdLessThan(String value) {
			addCriterion("md5_user_id <", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdLessThanOrEqualTo(String value) {
			addCriterion("md5_user_id <=", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdLike(String value) {
			addCriterion("md5_user_id like", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdNotLike(String value) {
			addCriterion("md5_user_id not like", value, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdIn(List<String> values) {
			addCriterion("md5_user_id in", values, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdNotIn(List<String> values) {
			addCriterion("md5_user_id not in", values, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdBetween(String value1, String value2) {
			addCriterion("md5_user_id between", value1, value2, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdNotBetween(String value1, String value2) {
			addCriterion("md5_user_id not between", value1, value2, "md5UserId");
			return (Criteria) this;
		}

		public Criteria andNickNameIsNull() {
			addCriterion("nick_name is null");
			return (Criteria) this;
		}

		public Criteria andNickNameIsNotNull() {
			addCriterion("nick_name is not null");
			return (Criteria) this;
		}

		public Criteria andNickNameEqualTo(String value) {
			addCriterion("nick_name =", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameNotEqualTo(String value) {
			addCriterion("nick_name <>", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameGreaterThan(String value) {
			addCriterion("nick_name >", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameGreaterThanOrEqualTo(String value) {
			addCriterion("nick_name >=", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameLessThan(String value) {
			addCriterion("nick_name <", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameLessThanOrEqualTo(String value) {
			addCriterion("nick_name <=", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameLike(String value) {
			addCriterion("nick_name like", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameNotLike(String value) {
			addCriterion("nick_name not like", value, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameIn(List<String> values) {
			addCriterion("nick_name in", values, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameNotIn(List<String> values) {
			addCriterion("nick_name not in", values, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameBetween(String value1, String value2) {
			addCriterion("nick_name between", value1, value2, "nickName");
			return (Criteria) this;
		}

		public Criteria andNickNameNotBetween(String value1, String value2) {
			addCriterion("nick_name not between", value1, value2, "nickName");
			return (Criteria) this;
		}

		public Criteria andBirthDayIsNull() {
			addCriterion("birth_day is null");
			return (Criteria) this;
		}

		public Criteria andBirthDayIsNotNull() {
			addCriterion("birth_day is not null");
			return (Criteria) this;
		}

		public Criteria andBirthDayEqualTo(Date value) {
			addCriterion("birth_day =", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayNotEqualTo(Date value) {
			addCriterion("birth_day <>", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayGreaterThan(Date value) {
			addCriterion("birth_day >", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayGreaterThanOrEqualTo(Date value) {
			addCriterion("birth_day >=", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayLessThan(Date value) {
			addCriterion("birth_day <", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayLessThanOrEqualTo(Date value) {
			addCriterion("birth_day <=", value, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayIn(List<Date> values) {
			addCriterion("birth_day in", values, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayNotIn(List<Date> values) {
			addCriterion("birth_day not in", values, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayBetween(Date value1, Date value2) {
			addCriterion("birth_day between", value1, value2, "birthDay");
			return (Criteria) this;
		}

		public Criteria andBirthDayNotBetween(Date value1, Date value2) {
			addCriterion("birth_day not between", value1, value2, "birthDay");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Byte value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Byte value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Byte value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Byte value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Byte value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Byte> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Byte> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Byte value1, Byte value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Byte value1, Byte value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andIntroIsNull() {
			addCriterion("intro is null");
			return (Criteria) this;
		}

		public Criteria andIntroIsNotNull() {
			addCriterion("intro is not null");
			return (Criteria) this;
		}

		public Criteria andIntroEqualTo(String value) {
			addCriterion("intro =", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotEqualTo(String value) {
			addCriterion("intro <>", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroGreaterThan(String value) {
			addCriterion("intro >", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroGreaterThanOrEqualTo(String value) {
			addCriterion("intro >=", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLessThan(String value) {
			addCriterion("intro <", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLessThanOrEqualTo(String value) {
			addCriterion("intro <=", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLike(String value) {
			addCriterion("intro like", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotLike(String value) {
			addCriterion("intro not like", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroIn(List<String> values) {
			addCriterion("intro in", values, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotIn(List<String> values) {
			addCriterion("intro not in", values, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroBetween(String value1, String value2) {
			addCriterion("intro between", value1, value2, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotBetween(String value1, String value2) {
			addCriterion("intro not between", value1, value2, "intro");
			return (Criteria) this;
		}

		public Criteria andUuidIsNull() {
			addCriterion("uuid is null");
			return (Criteria) this;
		}

		public Criteria andUuidIsNotNull() {
			addCriterion("uuid is not null");
			return (Criteria) this;
		}

		public Criteria andUuidEqualTo(String value) {
			addCriterion("uuid =", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotEqualTo(String value) {
			addCriterion("uuid <>", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThan(String value) {
			addCriterion("uuid >", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThanOrEqualTo(String value) {
			addCriterion("uuid >=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThan(String value) {
			addCriterion("uuid <", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThanOrEqualTo(String value) {
			addCriterion("uuid <=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLike(String value) {
			addCriterion("uuid like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotLike(String value) {
			addCriterion("uuid not like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidIn(List<String> values) {
			addCriterion("uuid in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotIn(List<String> values) {
			addCriterion("uuid not in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidBetween(String value1, String value2) {
			addCriterion("uuid between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotBetween(String value1, String value2) {
			addCriterion("uuid not between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andPassCodeIsNull() {
			addCriterion("pass_code is null");
			return (Criteria) this;
		}

		public Criteria andPassCodeIsNotNull() {
			addCriterion("pass_code is not null");
			return (Criteria) this;
		}

		public Criteria andPassCodeEqualTo(String value) {
			addCriterion("pass_code =", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeNotEqualTo(String value) {
			addCriterion("pass_code <>", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeGreaterThan(String value) {
			addCriterion("pass_code >", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeGreaterThanOrEqualTo(String value) {
			addCriterion("pass_code >=", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeLessThan(String value) {
			addCriterion("pass_code <", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeLessThanOrEqualTo(String value) {
			addCriterion("pass_code <=", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeLike(String value) {
			addCriterion("pass_code like", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeNotLike(String value) {
			addCriterion("pass_code not like", value, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeIn(List<String> values) {
			addCriterion("pass_code in", values, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeNotIn(List<String> values) {
			addCriterion("pass_code not in", values, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeBetween(String value1, String value2) {
			addCriterion("pass_code between", value1, value2, "passCode");
			return (Criteria) this;
		}

		public Criteria andPassCodeNotBetween(String value1, String value2) {
			addCriterion("pass_code not between", value1, value2, "passCode");
			return (Criteria) this;
		}

		public Criteria andUuidTokenIsNull() {
			addCriterion("uuid_token is null");
			return (Criteria) this;
		}

		public Criteria andUuidTokenIsNotNull() {
			addCriterion("uuid_token is not null");
			return (Criteria) this;
		}

		public Criteria andUuidTokenEqualTo(String value) {
			addCriterion("uuid_token =", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenNotEqualTo(String value) {
			addCriterion("uuid_token <>", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenGreaterThan(String value) {
			addCriterion("uuid_token >", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenGreaterThanOrEqualTo(String value) {
			addCriterion("uuid_token >=", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenLessThan(String value) {
			addCriterion("uuid_token <", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenLessThanOrEqualTo(String value) {
			addCriterion("uuid_token <=", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenLike(String value) {
			addCriterion("uuid_token like", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenNotLike(String value) {
			addCriterion("uuid_token not like", value, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenIn(List<String> values) {
			addCriterion("uuid_token in", values, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenNotIn(List<String> values) {
			addCriterion("uuid_token not in", values, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenBetween(String value1, String value2) {
			addCriterion("uuid_token between", value1, value2, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andUuidTokenNotBetween(String value1, String value2) {
			addCriterion("uuid_token not between", value1, value2, "uuidToken");
			return (Criteria) this;
		}

		public Criteria andOldUuidIsNull() {
			addCriterion("old_uuid is null");
			return (Criteria) this;
		}

		public Criteria andOldUuidIsNotNull() {
			addCriterion("old_uuid is not null");
			return (Criteria) this;
		}

		public Criteria andOldUuidEqualTo(String value) {
			addCriterion("old_uuid =", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidNotEqualTo(String value) {
			addCriterion("old_uuid <>", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidGreaterThan(String value) {
			addCriterion("old_uuid >", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidGreaterThanOrEqualTo(String value) {
			addCriterion("old_uuid >=", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidLessThan(String value) {
			addCriterion("old_uuid <", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidLessThanOrEqualTo(String value) {
			addCriterion("old_uuid <=", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidLike(String value) {
			addCriterion("old_uuid like", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidNotLike(String value) {
			addCriterion("old_uuid not like", value, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidIn(List<String> values) {
			addCriterion("old_uuid in", values, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidNotIn(List<String> values) {
			addCriterion("old_uuid not in", values, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidBetween(String value1, String value2) {
			addCriterion("old_uuid between", value1, value2, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andOldUuidNotBetween(String value1, String value2) {
			addCriterion("old_uuid not between", value1, value2, "oldUuid");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIsNull() {
			addCriterion("migrate_id is null");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIsNotNull() {
			addCriterion("migrate_id is not null");
			return (Criteria) this;
		}

		public Criteria andMigrateIdEqualTo(String value) {
			addCriterion("migrate_id =", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdNotEqualTo(String value) {
			addCriterion("migrate_id <>", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdGreaterThan(String value) {
			addCriterion("migrate_id >", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdGreaterThanOrEqualTo(String value) {
			addCriterion("migrate_id >=", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdLessThan(String value) {
			addCriterion("migrate_id <", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdLessThanOrEqualTo(String value) {
			addCriterion("migrate_id <=", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdLike(String value) {
			addCriterion("migrate_id like", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdNotLike(String value) {
			addCriterion("migrate_id not like", value, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIn(List<String> values) {
			addCriterion("migrate_id in", values, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdNotIn(List<String> values) {
			addCriterion("migrate_id not in", values, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdBetween(String value1, String value2) {
			addCriterion("migrate_id between", value1, value2, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdNotBetween(String value1, String value2) {
			addCriterion("migrate_id not between", value1, value2, "migrateId");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateIsNull() {
			addCriterion("migrate_id_issue_date is null");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateIsNotNull() {
			addCriterion("migrate_id_issue_date is not null");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateEqualTo(Date value) {
			addCriterion("migrate_id_issue_date =", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateNotEqualTo(Date value) {
			addCriterion("migrate_id_issue_date <>", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateGreaterThan(Date value) {
			addCriterion("migrate_id_issue_date >", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateGreaterThanOrEqualTo(Date value) {
			addCriterion("migrate_id_issue_date >=", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateLessThan(Date value) {
			addCriterion("migrate_id_issue_date <", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateLessThanOrEqualTo(Date value) {
			addCriterion("migrate_id_issue_date <=", value, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateIn(List<Date> values) {
			addCriterion("migrate_id_issue_date in", values, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateNotIn(List<Date> values) {
			addCriterion("migrate_id_issue_date not in", values, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateBetween(Date value1, Date value2) {
			addCriterion("migrate_id_issue_date between", value1, value2, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andMigrateIdIssueDateNotBetween(Date value1, Date value2) {
			addCriterion("migrate_id_issue_date not between", value1, value2, "migrateIdIssueDate");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeIsNull() {
			addCriterion("deck_pattern_type is null");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeIsNotNull() {
			addCriterion("deck_pattern_type is not null");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeEqualTo(Byte value) {
			addCriterion("deck_pattern_type =", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeNotEqualTo(Byte value) {
			addCriterion("deck_pattern_type <>", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeGreaterThan(Byte value) {
			addCriterion("deck_pattern_type >", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("deck_pattern_type >=", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeLessThan(Byte value) {
			addCriterion("deck_pattern_type <", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeLessThanOrEqualTo(Byte value) {
			addCriterion("deck_pattern_type <=", value, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeIn(List<Byte> values) {
			addCriterion("deck_pattern_type in", values, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeNotIn(List<Byte> values) {
			addCriterion("deck_pattern_type not in", values, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeBetween(Byte value1, Byte value2) {
			addCriterion("deck_pattern_type between", value1, value2, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andDeckPatternTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("deck_pattern_type not between", value1, value2, "deckPatternType");
			return (Criteria) this;
		}

		public Criteria andUserStatusIsNull() {
			addCriterion("user_status is null");
			return (Criteria) this;
		}

		public Criteria andUserStatusIsNotNull() {
			addCriterion("user_status is not null");
			return (Criteria) this;
		}

		public Criteria andUserStatusEqualTo(Byte value) {
			addCriterion("user_status =", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotEqualTo(Byte value) {
			addCriterion("user_status <>", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusGreaterThan(Byte value) {
			addCriterion("user_status >", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("user_status >=", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusLessThan(Byte value) {
			addCriterion("user_status <", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusLessThanOrEqualTo(Byte value) {
			addCriterion("user_status <=", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusIn(List<Byte> values) {
			addCriterion("user_status in", values, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotIn(List<Byte> values) {
			addCriterion("user_status not in", values, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusBetween(Byte value1, Byte value2) {
			addCriterion("user_status between", value1, value2, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("user_status not between", value1, value2, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andMd5UserIdLikeInsensitive(String value) {
			addCriterion("upper(md5_user_id) like", value.toUpperCase(), "md5UserId");
			return (Criteria) this;
		}

		public Criteria andNickNameLikeInsensitive(String value) {
			addCriterion("upper(nick_name) like", value.toUpperCase(), "nickName");
			return (Criteria) this;
		}

		public Criteria andIntroLikeInsensitive(String value) {
			addCriterion("upper(intro) like", value.toUpperCase(), "intro");
			return (Criteria) this;
		}

		public Criteria andUuidLikeInsensitive(String value) {
			addCriterion("upper(uuid) like", value.toUpperCase(), "uuid");
			return (Criteria) this;
		}

		public Criteria andPassCodeLikeInsensitive(String value) {
			addCriterion("upper(pass_code) like", value.toUpperCase(), "passCode");
			return (Criteria) this;
		}

		public Criteria andUuidTokenLikeInsensitive(String value) {
			addCriterion("upper(uuid_token) like", value.toUpperCase(), "uuidToken");
			return (Criteria) this;
		}

		public Criteria andOldUuidLikeInsensitive(String value) {
			addCriterion("upper(old_uuid) like", value.toUpperCase(), "oldUuid");
			return (Criteria) this;
		}

		public Criteria andMigrateIdLikeInsensitive(String value) {
			addCriterion("upper(migrate_id) like", value.toUpperCase(), "migrateId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table i_user
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table i_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}