package jp.takuya152005.entities.dto;

import java.io.Serializable;

public class IUserKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.user_id
	 * @mbggenerated
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	private Integer tableNameSuffix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.user_id
	 * @return  the value of i_user.user_id
	 * @mbggenerated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.user_id
	 * @param userId  the value for i_user.user_id
	 * @mbggenerated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public Integer getTableNameSuffix() {
		return tableNameSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	public void setTableNameSuffix(Integer tableNameSuffix) {
		this.tableNameSuffix = tableNameSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", tableNameSuffix=").append(tableNameSuffix);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}