package jp.takuya152005.entities.dto;

import java.io.Serializable;
import java.util.Date;

public class IUser extends IUserKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.md5_user_id
	 * @mbggenerated
	 */
	private String md5UserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.nick_name
	 * @mbggenerated
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.birth_day
	 * @mbggenerated
	 */
	private Date birthDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.gender
	 * @mbggenerated
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.intro
	 * @mbggenerated
	 */
	private String intro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.uuid
	 * @mbggenerated
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.pass_code
	 * @mbggenerated
	 */
	private String passCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.uuid_token
	 * @mbggenerated
	 */
	private String uuidToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.old_uuid
	 * @mbggenerated
	 */
	private String oldUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.migrate_id
	 * @mbggenerated
	 */
	private String migrateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.migrate_id_issue_date
	 * @mbggenerated
	 */
	private Date migrateIdIssueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.deck_pattern_type
	 * @mbggenerated
	 */
	private Byte deckPatternType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.user_status
	 * @mbggenerated
	 */
	private Byte userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.update_datetime
	 * @mbggenerated
	 */
	private Date updateDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column i_user.insert_datetime
	 * @mbggenerated
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table i_user
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.md5_user_id
	 * @return  the value of i_user.md5_user_id
	 * @mbggenerated
	 */
	public String getMd5UserId() {
		return md5UserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.md5_user_id
	 * @param md5UserId  the value for i_user.md5_user_id
	 * @mbggenerated
	 */
	public void setMd5UserId(String md5UserId) {
		this.md5UserId = md5UserId == null ? null : md5UserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.nick_name
	 * @return  the value of i_user.nick_name
	 * @mbggenerated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.nick_name
	 * @param nickName  the value for i_user.nick_name
	 * @mbggenerated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.birth_day
	 * @return  the value of i_user.birth_day
	 * @mbggenerated
	 */
	public Date getBirthDay() {
		return birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.birth_day
	 * @param birthDay  the value for i_user.birth_day
	 * @mbggenerated
	 */
	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.gender
	 * @return  the value of i_user.gender
	 * @mbggenerated
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.gender
	 * @param gender  the value for i_user.gender
	 * @mbggenerated
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.intro
	 * @return  the value of i_user.intro
	 * @mbggenerated
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.intro
	 * @param intro  the value for i_user.intro
	 * @mbggenerated
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.uuid
	 * @return  the value of i_user.uuid
	 * @mbggenerated
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.uuid
	 * @param uuid  the value for i_user.uuid
	 * @mbggenerated
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid == null ? null : uuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.pass_code
	 * @return  the value of i_user.pass_code
	 * @mbggenerated
	 */
	public String getPassCode() {
		return passCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.pass_code
	 * @param passCode  the value for i_user.pass_code
	 * @mbggenerated
	 */
	public void setPassCode(String passCode) {
		this.passCode = passCode == null ? null : passCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.uuid_token
	 * @return  the value of i_user.uuid_token
	 * @mbggenerated
	 */
	public String getUuidToken() {
		return uuidToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.uuid_token
	 * @param uuidToken  the value for i_user.uuid_token
	 * @mbggenerated
	 */
	public void setUuidToken(String uuidToken) {
		this.uuidToken = uuidToken == null ? null : uuidToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.old_uuid
	 * @return  the value of i_user.old_uuid
	 * @mbggenerated
	 */
	public String getOldUuid() {
		return oldUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.old_uuid
	 * @param oldUuid  the value for i_user.old_uuid
	 * @mbggenerated
	 */
	public void setOldUuid(String oldUuid) {
		this.oldUuid = oldUuid == null ? null : oldUuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.migrate_id
	 * @return  the value of i_user.migrate_id
	 * @mbggenerated
	 */
	public String getMigrateId() {
		return migrateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.migrate_id
	 * @param migrateId  the value for i_user.migrate_id
	 * @mbggenerated
	 */
	public void setMigrateId(String migrateId) {
		this.migrateId = migrateId == null ? null : migrateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.migrate_id_issue_date
	 * @return  the value of i_user.migrate_id_issue_date
	 * @mbggenerated
	 */
	public Date getMigrateIdIssueDate() {
		return migrateIdIssueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.migrate_id_issue_date
	 * @param migrateIdIssueDate  the value for i_user.migrate_id_issue_date
	 * @mbggenerated
	 */
	public void setMigrateIdIssueDate(Date migrateIdIssueDate) {
		this.migrateIdIssueDate = migrateIdIssueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.deck_pattern_type
	 * @return  the value of i_user.deck_pattern_type
	 * @mbggenerated
	 */
	public Byte getDeckPatternType() {
		return deckPatternType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.deck_pattern_type
	 * @param deckPatternType  the value for i_user.deck_pattern_type
	 * @mbggenerated
	 */
	public void setDeckPatternType(Byte deckPatternType) {
		this.deckPatternType = deckPatternType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.user_status
	 * @return  the value of i_user.user_status
	 * @mbggenerated
	 */
	public Byte getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.user_status
	 * @param userStatus  the value for i_user.user_status
	 * @mbggenerated
	 */
	public void setUserStatus(Byte userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.update_datetime
	 * @return  the value of i_user.update_datetime
	 * @mbggenerated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.update_datetime
	 * @param updateDatetime  the value for i_user.update_datetime
	 * @mbggenerated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column i_user.insert_datetime
	 * @return  the value of i_user.insert_datetime
	 * @mbggenerated
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column i_user.insert_datetime
	 * @param insertDatetime  the value for i_user.insert_datetime
	 * @mbggenerated
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table i_user
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", md5UserId=").append(md5UserId);
		sb.append(", nickName=").append(nickName);
		sb.append(", birthDay=").append(birthDay);
		sb.append(", gender=").append(gender);
		sb.append(", intro=").append(intro);
		sb.append(", uuid=").append(uuid);
		sb.append(", passCode=").append(passCode);
		sb.append(", uuidToken=").append(uuidToken);
		sb.append(", oldUuid=").append(oldUuid);
		sb.append(", migrateId=").append(migrateId);
		sb.append(", migrateIdIssueDate=").append(migrateIdIssueDate);
		sb.append(", deckPatternType=").append(deckPatternType);
		sb.append(", userStatus=").append(userStatus);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append(", insertDatetime=").append(insertDatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}